doctrine:
  dbal:
    types:
      modules-backend-navigation-action_slug: ForkCMS\Modules\Backend\Domain\NavigationItem\ActionSlugDBALType

  orm:
    mappings:
      backend_navigation:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Modules/Backend/Domain/Navigation"
        alias: BackendNavigation
        prefix: ForkCMS\Modules\Backend\Domain\NavigationItem
