backend_ajax:
  path: /backend/ajax
  controller: ForkCMS\Modules\Backend\Controller\BackendAjaxController

backend_logout:
  path: /private/{_locale}/backend/authentication_logout

backend_login:
  path: /private/{_locale}/backend/authentication_login
  controller: ForkCMS\Modules\Backend\Controller\LoginController

backend:
  path: /private/{_locale}/{module}/{action}
  controller: ForkCMS\Modules\Backend\Controller\BackendController
  defaults:
    module: ~
    action: ~
