services:
  _defaults:
    autowire: true
    autoconfigure: true

  ForkCMS\Modules\Backend\Domain\:
    resource: '../Domain/*'

  ForkCMS\Modules\Backend\Backend\:
    resource: '../Backend/*'

  ForkCMS\Modules\Backend\Console\:
    resource: '../Console/*'

  ForkCMS\Modules\Backend\DataFixtures\:
    resource: '../DataFixtures/*'

  ForkCMS\Modules\Backend\DependencyInjection\BackendRouteLoader: ~