services:
  _defaults:
    autowire: true
    autoconfigure: true

  ForkCMS\Modules\Backend\Domain\:
    resource: '../Domain/*'

  ForkCMS\Modules\Backend\Backend\Actions\:
    resource: '../Backend/Actions/*'

  Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider: ~

  ForkCMS\Modules\Backend\Backend\Actions\NotFound:
    public: true

  ForkCMS\Modules\Backend\DependencyInjection\BackendRouteLoader:
    arguments:
      - '@routing.loader.yml'
