services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

#    ForkCMS\Modules\Pages\Domain\Page\Command\CopyPagesToOtherLocaleHandler:
#        tags:
#            - { name: command_handler, handles: ForkCMS\Modules\Pages\Domain\Page\Command\CopyPagesToOtherLocale }
#
#    ForkCMS\Modules\Pages\Domain\Page\Command\CreatePageHandler:
#        tags:
#            - { name: command_handler, handles: ForkCMS\Modules\Pages\Domain\Page\Command\CreatePage }
#
#    ForkCMS\Modules\Pages\Domain\Page\Command\UpdatePageHandler:
#        tags:
#            - { name: command_handler, handles: ForkCMS\Modules\Pages\Domain\Page\Command\UpdatePage }
