doctrine:
    dbal:
        types:
            module_extra_type: ForkCMS\Modules\Pages\Domain\ModuleExtra\ModuleExtraDBALType
            pages_page_block_type: ForkCMS\Modules\Pages\Domain\PageBlock\TypeDBALType
            page_status: ForkCMS\Modules\Pages\Domain\Page\StatusDBALType
            pages_page_type: ForkCMS\Modules\Pages\Domain\Page\TypeDBALType
    orm:
        mappings:
            module_extra:
                type: annotation
                is_bundle: false
                dir: "%kernel.project_dir%/src/Modules/Pages/Domain/ModuleExtra"
                alias: PagesModuleExtra
                prefix: ForkCMS\Modules\Pages\Domain\ModuleExtra
            page_block:
                type: annotation
                is_bundle: false
                dir: "%kernel.project_dir%/src/Modules/Pages/Domain/PageBlock"
                alias: PagesPageBlock
                prefix: ForkCMS\Modules\Pages\Domain\PageBlock
            page:
                type: annotation
                is_bundle: false
                dir: "%kernel.project_dir%/src/Modules/Pages/Domain/Page"
                alias: PagesPage
                prefix: ForkCMS\Modules\Pages\Domain\Page
