services:
  _defaults:
    autowire: true
    autoconfigure: true

  ForkCMS\Modules\Pages\Domain\:
    resource: '../Domain/*'

  ForkCMS\Modules\Pages\Controller\:
    resource: '../Controller/*'
    public: true

  ForkCMS\Modules\Pages\DependencyInjection\PagesRouteLoader:
