services:
    formbuilder.submitted.mailer:
        class: Frontend\Modules\FormBuilder\EventListener\FormBuilderSubmittedMailSubscriber
        arguments:
            - "@mailer"
            - '@Common\ModulesSettings'
        tags:
            - { name: kernel.event_listener, event: form.submitted, method: onFormSubmitted }
