#services:
#    formbuilder.submitted.mailer:
#        class: ForkCMS\Modules\FormBuilder\Frontend\Helper\FormBuilderSubmittedMailSubscriber
#        arguments:
#            - "@mailer"
#            - '@ForkCMS\Modules\Extensions\Domain\ModuleSetting\ModuleSettingRepository'
#        tags:
#            - { name: kernel.event_listener, event: form.submitted, method: onFormSubmitted }
