doctrine:
  dbal:
    types:
      modules-extensions-module-module_name: ForkCMS\Modules\Extensions\Domain\Module\ModuleNameDBALType
  orm:
    mappings:
      extensions_module:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Modules/Extensions/Domain/Module"
        alias: ExtensionsModule
        prefix: ForkCMS\Modules\Extensions\Domain\Module
