services:
  _defaults:
    autowire: true
    autoconfigure: true

  ForkCMS\Modules\Extensions\Domain\:
    resource: '../Domain/*'
    exclude:
      - '../Domain/Module/InstalledModules'

  ForkCMS\Modules\Extensions\Domain\ModuleSetting\ModuleSettingRepository:
    public: true
