services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $commandBus: '@command_bus' # Generic // This should be replaced with the Messenger component

    Backend\Modules\MediaGalleries\Console\MediaGalleryDeleteAllCommand:
        tags:
            - { name: console.command }
