services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Backend\Modules\Faq\Domain\Category\Command\CreateCategoryHandler:
    tags:
      - { name: command_handler, handles: Backend\Modules\Faq\Domain\Category\Command\CreateCategory }

  Backend\Modules\Faq\Domain\Category\Command\DeleteCategoryHandler:
    tags:
      - { name: command_handler, handles: Backend\Modules\Faq\Domain\Category\Command\DeleteCategory }

  Backend\Modules\Faq\Domain\Category\Command\UpdateCategoryHandler:
    tags:
      - { name: command_handler, handles: Backend\Modules\Faq\Domain\Category\Command\UpdateCategory }

  Backend\Modules\Faq\Domain\Category\Command\ReSequenceCategoriesHandler:
    tags:
      - { name: command_handler, handles: Backend\Modules\Faq\Domain\Category\Command\ReSequenceCategories }

  Backend\Modules\Faq\Domain\Question\Command\CreateQuestionHandler:
    tags:
      - { name: command_handler, handles: Backend\Modules\Faq\Domain\Question\Command\CreateQuestion }

  Backend\Modules\Faq\Domain\Question\Command\DeleteQuestionHandler:
    tags:
      - { name: command_handler, handles: Backend\Modules\Faq\Domain\Question\Command\DeleteQuestion }

  Backend\Modules\Faq\Domain\Question\Command\UpdateQuestionHandler:
    tags:
      - { name: command_handler, handles: Backend\Modules\Faq\Domain\Question\Command\UpdateQuestion }
