services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Backend\Modules\Faq\Domain\Category\CategoryRepository:
        public: true

    Backend\Modules\Faq\Domain\Question\QuestionRepository:
        public: true

    Backend\Modules\Faq\Domain\Feedback\FeedbackRepository:
        public: true
