services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\CreateContentBlockHandler:
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\CreateContentBlock }

    Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\UpdateContentBlockHandler:
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\UpdateContentBlock }

    Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\DeleteContentBlockHandler:
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\DeleteContentBlock }

    Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\CopyContentBlocksToOtherLocaleHandler:
        tags:
            - { name: command_handler, handles: Backend\Modules\ContentBlocks\Domain\ContentBlock\Command\CopyContentBlocksToOtherLocale }
