# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%kernel.secret%'
  csrf_protection: true
  #http_method_override: true

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: 'session.handler.native_file'

  #esi: true
  #fragments: true
  php_errors:
    log: true


  router:
#    resource: "%kernel.project_dir%/config/routing.yml"
    strict_requirements: ~
  serializer: true
  assets:
    packages: # create the "assets.packages" service
  form: ~
