# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/"
        cache_prefix: src/Frontend/Files/Cache
  loaders:
    default:
      filesystem:
        data_root: "%kernel.project_dir%/"
        locator: filesystem_insecure
  cache: default
  data_loader: default

  # your filter sets are defined here
  filter_sets:
    # the name of the "filter set"
    media_library_backend_thumbnail:
      # adjust the image quality to 95%
      quality: 95
      # list of transformations to apply (the "filters")
      filters:
        # auto rotate the image using EXIF metadata and then strip the metadata (privacy)
        auto_rotate: ~
        strip: ~

        ## Using the "thumbnail + background" combination will crop the
        ## the centered image to create your required width/height.
        # Use the "outbound" mode to crop the image when the size ratio of the input differs
        thumbnail: { size: [ 140, 90 ], mode: outbound }
        background: { size: [ 140, 90 ], position: center }
    media_library_lightbox_small:
      filters:
        # auto rotate the image using EXIF metadata and then strip the metadata (privacy)
        auto_rotate: ~
        strip: ~

        scale: { dim: [ 800, 600 ] }
    media_library_lightbox_large:
      filters:
        # auto rotate the image using EXIF metadata and then strip the metadata (privacy)
        auto_rotate: ~
        strip: ~

        scale: { dim: [ 1600, 800 ] }
    media_library_slider_pano:
      filters:
        # auto rotate the image using EXIF metadata and then strip the metadata (privacy)
        auto_rotate: ~
        strip: ~

        scale: { dim: [ 1600, 600 ] }
    media_library_one_image_large:
      filters:
        # auto rotate the image using EXIF metadata and then strip the metadata (privacy)
        auto_rotate: ~
        strip: ~

        thumbnail: { size: [ 1600, 500 ], mode: inbound }
    media_library_editor_image:
      filters:
        # auto rotate the image using EXIF metadata and then strip the metadata (privacy)
        auto_rotate: ~
        strip: ~

        scale: { dim: [ 2400, 2400 ] }

services:
  liip_imagine.cache.manager.public:
    alias: liip_imagine.cache.manager
    public: true
