twig:
  default_path: '%kernel.project_dir%/templates'
#  debug: "%kernel.debug%"
#  strict_variables: "%kernel.debug%"
#  form_themes:
#    - '%fork.form.theme%'
#  paths:
#    '%site.path_www%/src/Frontend/Modules/': ForkFrontendModules
