doctrine:
  orm:
    mappings:
      location:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Modules/Location/Domain"
        alias: LocationLocation
        prefix: ForkCMS\Modules\Location\Domain
