services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ForkCMS\Modules\Location\Domain\Location\LocationRepository:

    ForkCMS\Modules\Location\Domain\LocationSetting\LocationSettingRepository:
