imports:
    - { resource: base_config.yml }
    - { resource: parameters_install.yml }

parameters:
    doctrine.dbal.connection_factory.class: ForkCMS\Bundle\InstallerBundle\Service\InstallerConnectionFactory
    fork.is_installed: false
    fork.form.theme: "ForkCMSInstallerBundle:Installer:form_theme.html.twig"

twig: ~

framework:
    secret: "%kernel.secret%"
    router:
        resource: "%kernel.project_dir%/app/config/routing_install.yml"

monolog:
    handlers:
        main:
            type: stream
            path: "%site.path_www%/var/logs/%kernel.environment%/debug.log"
            level: debug

services:
    templating:
        alias: templating.engine.twig

    fork.settings:
        class: Common\ModulesSettings
        public: true
        arguments:
            - "@database"
            - "@cache.pool"
            - "%fork.is_installed%"

    # dummy service during the installation
    mailer_configurator:
        class: stdClass

    cache.pool:
        class: Symfony\Component\Cache\Adapter\ArrayAdapter

    database:
        class: SpoonDatabase
        public: true
        arguments:
            - "%database.driver%"
            - "%database.host%"
            - "%database.user%"
            - "%database.password%"
            - "%database.name%"
            - "%database.port%"
        calls:
            - [ setDebug, [ "%kernel.debug%" ]]

# Doctrine Configuration
doctrine:
    dbal:
        types:
            locale: ForkCMS\Bundle\InstallerBundle\DBALType\LocaleDBALType
