services:
  mailmotor.listener.settings_saved:
    class: ForkCMS\Modules\Mailmotor\EventListener\SettingsSavedListener
    arguments:
      - "%kernel.cache_dir%"
    tags:
      - { name: kernel.event_listener, event: mailmotor.event.settings_saved, method: onSettingsSavedEvent }
  mailmotor.listener.subscribed:
    class: Frontend\Modules\Mailmotor\EventListener\NewNotImplementedMailingListSubscription
    arguments:
      - "@mailer"
      - '@ForkCMS\Modules\Extensions\Domain\ModuleSetting\ModuleSettingRepository'
    tags:
      - { name: kernel.event_listener, event: mailmotor.event.not_implemented.subscribed, method: onNotImplementedSubscribedEvent }
  mailmotor.listener.unsubscribed:
    class: Frontend\Modules\Mailmotor\EventListener\NewNotImplementedMailingListUnsubscription
    arguments:
      - "@mailer"
      - '@ForkCMS\Modules\Extensions\Domain\ModuleSetting\ModuleSettingRepository'
    tags:
      - { name: kernel.event_listener, event: mailmotor.event.not_implemented.unsubscribed, method: onNotImplementedUnsubscribedEvent }

  Frontend\Modules\Mailmotor\EventListener\FormBuilderSubmittedMailmotorSubscriber:
    arguments:
        - '@ForkCMS\Modules\Extensions\Domain\ModuleSetting\ModuleSettingRepository'
        - "@mailmotor.subscriber"
    tags:
        - { name: kernel.event_listener, event: form.submitted, method: onFormSubmitted }
