#services:
#    media_library.cache.media_folder:
#        class: ForkCMS\Modules\MediaLibrary\Builder\MediaFolder\MediaFolderCache
#        public: true
#        arguments:
#            - "@cache.pool"
#            - "@service_container"
