services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # MediaFolder
    media_galleries.handler.create_media_folder:
        class: ForkCMS\Modules\MediaLibrary\Domain\MediaFolder\Command\CreateMediaFolderHandler
        tags:
            - { name: command_handler, handles: ForkCMS\Modules\MediaLibrary\Domain\MediaFolder\Command\CreateMediaFolder }

    media_galleries.handler.delete_media_folder:
        class: ForkCMS\Modules\MediaLibrary\Domain\MediaFolder\Command\DeleteMediaFolderHandler
        tags:
            - { name: command_handler, handles: ForkCMS\Modules\MediaLibrary\Domain\MediaFolder\Command\DeleteMediaFolder }

    media_galleries.handler.update_media_folder:
        class: ForkCMS\Modules\MediaLibrary\Domain\MediaFolder\Command\UpdateMediaFolderHandler
        tags:
            - { name: command_handler, handles: ForkCMS\Modules\MediaLibrary\Domain\MediaFolder\Command\UpdateMediaFolder }

    # MediaGroup
    media_galleries.handler.update_media_group:
        class: ForkCMS\Modules\MediaLibrary\Domain\MediaGroup\Command\SaveMediaGroupHandler
        tags:
            - { name: command_handler, handles: ForkCMS\Modules\MediaLibrary\Domain\MediaGroup\Command\SaveMediaGroup }

    # MediaItem
    media_galleries.handler.create_media_item_from_movie_url:
        class: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\Command\CreateMediaItemFromMovieUrlHandler
        tags:
            - { name: command_handler, handles: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\Command\CreateMediaItemFromMovieUrl }

    media_galleries.handler.create_media_item_from_local_source:
        class: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\Command\CreateMediaItemFromLocalStorageTypeHandler
        tags:
            - { name: command_handler, handles: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\Command\CreateMediaItemFromLocalStorageType }

    media_library.handler.delete_media_item:
        class: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\Command\DeleteMediaItemHandler
        tags:
            - { name: command_handler, handles: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\Command\DeleteMediaItem }

    media_galleries.handler.update_media_item:
        class: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\Command\UpdateMediaItemHandler
        tags:
            - { name: command_handler, handles: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\Command\UpdateMediaItem }
