#services:
#    _defaults:
#        autowire: true
#        autoconfigure: true
#
#    ForkCMS\Modules\MediaLibrary\Console\CacheClearCommand:
#        tags:
#            -  { name: console.command }
