doctrine:
  dbal:
    types:
      media_library__media_item__storage_type: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\StorageTypeDBALType
      media_library__media_item__type: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\TypeDBALType
      media_library__media_item__aspect_ratio: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\AspectRatioDBALType
      media_library__media_group__type: ForkCMS\Modules\MediaLibrary\Domain\MediaGroup\TypeDBALType
