doctrine:
  dbal:
    types:
      uuid: Ramsey\Uuid\Doctrine\UuidType
      media_item_storage_type: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\StorageTypeDBALType
      media_item_type: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\TypeDBALType
      media_item_aspect_ratio: ForkCMS\Modules\MediaLibrary\Domain\MediaItem\AspectRatioDBALType
      media_group_type: ForkCMS\Modules\MediaLibrary\Domain\MediaGroup\TypeDBALType
  orm:
    mappings:
      media_folder:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Modules/MediaLibrary/Domain/MediaFolder"
        alias: MediaLibraryMediaFolder
        prefix: ForkCMS\Modules\MediaLibrary\Domain\MediaFolder
      media_group:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Modules/MediaLibrary/Domain/MediaGroup"
        alias: MediaLibraryMediaGroup
        prefix: ForkCMS\Modules\MediaLibrary\Domain\MediaGroup
      media_group_media_item:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Modules/MediaLibrary/Domain/MediaGroupMediaItem"
        alias: MediaLibraryMediaGroupMediaItem
        prefix: ForkCMS\Modules\MediaLibrary\Domain\MediaGroupMediaItem
      media_item:
        type: annotation
        is_bundle: false
        dir: "%kernel.project_dir%/src/Modules/MediaLibrary/Domain/MediaItem"
        alias: MediaLibraryMediaItem
        prefix: ForkCMS\Modules\MediaLibrary\Domain\MediaItem
