#services:
#    media_library.listener.invalidate_backend_media_folder_cache:
#        class: ForkCMS\Modules\MediaLibrary\EventListener\MediaFolderInvalidateBackendCacheSubscriber
#        arguments:
#            - "@media_library.cache.media_folder"
#        tags:
#            - { name: doctrine.event_subscriber }
#    media_library.listener.media_item:
#        class: ForkCMS\Modules\MediaLibrary\EventListener\MediaItemSubscriber
#        tags:
#            - { name: doctrine.event_subscriber }
#        arguments:
#            - '@ForkCMS\Modules\MediaLibrary\Manager\FileManager'
#            - "@liip_imagine.cache.manager"
#            - "@command_bus"
#    media_library.listener.media_item_deleted_resequence:
#        class: ForkCMS\Modules\MediaLibrary\EventListener\MediaItemDeletedReSequenceMediaGroupMediaItemListener
#        arguments:
#            - "@command_bus"
#        tags:
#            - { name: doctrine.event_listener, event: postRemove }
