services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ForkCMS\Modules\MediaLibrary\Domain\MediaFolder\MediaFolderRepository:

    ForkCMS\Modules\MediaLibrary\Domain\MediaGroup\MediaGroupRepository:

    ForkCMS\Modules\MediaLibrary\Domain\MediaGroupMediaItem\MediaGroupMediaItemRepository:

    ForkCMS\Modules\MediaLibrary\Domain\MediaItem\MediaItemRepository:
