services:
  _defaults:
    autowire: true
    autoconfigure: true

  ForkCMS\Modules\Internationalisation\Console\:
    resource: '../Console/*'

  ForkCMS\Modules\Internationalisation\Domain\:
    resource: '../Domain/*'
    exclude:
      - '../Domain/Translator/ForkTranslator.php'
      - '../Domain/Importer/Importer.php'
      - '../Domain/Twig'

  ForkCMS\Modules\Internationalisation\Backend\:
    resource: '../Backend/*'

  ForkCMS\Modules\Internationalisation\Domain\Importer\Importer:

  ForkCMS\Modules\Internationalisation\DependencyInjection\InternationalisationRouteLoader: