services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $rootDir: '%kernel.project_dir%'

  ForkCMS\Modules\Internationalisation\Console\:
    resource: '../Console/*'

  ForkCMS\Modules\Internationalisation\Domain\:
    resource: '../Domain/*'
    exclude:
      - '../Domain/Translator/ForkTranslator.php'
      - '../Domain/Importer/Importer.php'

  ForkCMS\Modules\Internationalisation\Domain\Translation\ForkTranslationLoader:
    tags:
      - { name: translation.loader, alias: db }

  ForkCMS\Modules\Internationalisation\Domain\Importer\XmlImporter:
    arguments:
      - '%kernel.project_dir%'

  ForkCMS\Modules\Internationalisation\Domain\Importer\Importer:
    arguments:
      - !tagged_locator { tag: 'forkcms.translation.importer', default_index_method: 'forExtension' }
