monolog:
  handlers:
    main:
      type: rotating_file
      action_level: error
      path: "%kernel.logs_dir%/%kernel.environment%/error.log"
      handler: nested
      excluded_http_codes: [ 404, 405 ]
      max_files: 10
    nested:
      type: stream
      path: php://stderr
      level: debug
      formatter: monolog.formatter.json
    console:
      type: console
      process_psr_3_messages: false
      channels: [ "!event", "!doctrine" ]
    # swift:
    #     type:       swift_mailer
    #     from_email: %fork.debug_email%
    #     to_email:   %fork.debug_email%
    #     subject:    %site.default_title% %fork.debug_message%
    #     level:      error
    #     formatter:  monolog.formatter.html
    #     content_type: text/html
