doctrine:
  dbal:
    types:
      core_application_application: ForkCMS\Core\Domain\Application\ApplicationDBALType
      core_locale_locale: ForkCMS\Core\Domain\Locale\LocaleDBALType
      core_module_modulename: ForkCMS\Core\Domain\Module\ModuleNameDBALType
  orm:
    mappings:
