services:
  _defaults:
    autowire: true
    autoconfigure: true
  _instanceof:
    Symfony\Component\Console\Command\Command:
      bind:
        string $rootDir: '%kernel.project_dir%'
        string $cacheDir: '%kernel.cache_dir%'
        bool $forkIsInstalled: '%fork.is_installed%'

  ForkCMS\Core\:
    resource: '../*'
    exclude:
      - '../Installer'
      - '../Tests'

  ForkCMS\Core\Installer\Console\:
    resource: '../Installer/Console/*'

  ForkCMS\Core\Installer\Domain\Configuration\ConfigurationParser:
    arguments:
      $rootDir: '%kernel.project_dir%'

  module_installers:
    namespace: ForkCMS\Modules\
    resource: '../../Modules/*/Installer'

  ForkCMS\Core\Domain\Router\ModuleRouteLoader:
    arguments:
      - !tagged_iterator { tag: forkcms.routing.loader }
    tags:
      - { name: routing.loader }
