services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $rootDir: '%kernel.project_dir%'
      bool $forkIsInstalled: '%fork.is_installed%'

  ForkCMS\Core\:
    resource: '../*'
    exclude:
      - '../Installer'
      - '../Tests'

  ForkCMS\Core\Installer\Console\:
    resource: '../Installer/Console/*'

  module_installers:
    namespace: ForkCMS\Modules\
    resource: '../../Modules/*/Installer'
