services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $rootDir: '%kernel.project_dir%'

  ForkCMS\Core\:
    resource: '../*'
    exclude:
      - '../Backend/Domain/Meta/AddMetaSubscriber.php'
      - '../Common/DataCollector/DatabaseDataCollector.php'
      - '../Common/ForkCMS/Utility/Module/CopyContentToOtherLocale/CopyContentFromModulesToOtherLocaleManager.php'
      - '../Common/ForkCMS/Utility/Thumbnails.php'
      - '../Common/ModulesSettings.php'
      - '../Console/Locale/CopyLocaleCommand.php'
      - '../Console/Locale/EnableLocaleCommand.php'
      - '../Console/Thumbnails/GenerateThumbnailsCommand.php'
      - '../Installer'
      - '../Tests'

  ForkCMS\Modules\Extensions\Domain\Module\ModuleInstallerLocator:
    arguments:
      - !tagged_iterator { tag: 'forkcms.module.installer' }

  module_installers:
    namespace: ForkCMS\Modules\
    resource: '../../Modules/*/Installer'
