imports:
    - { resource: config_install.yaml }

parameters:
    site.multilanguage: true
    site.default_language: en

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    router:
        resource: "%kernel.project_dir%/config/routing_install.yaml"

monolog:
    handlers:
        main:
            type:  stream
            path:  "%site.path_www%/var/log/%kernel.environment%/debug.log"
            level: debug
