services:
  # default configuration for services in Fork when they import this file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    Symfony\Component\HttpKernel\Controller\ValueResolverInterface:
      tags:
        - { name: controller.argument_value_resolver, priority: 101 }

    Twig\Extension\ExtensionInterface:
      tags:
        - { name: twig.extension }