services:
  # default configuration for services in Fork when they import this file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    ForkCMS\Core\Domain\MessageHandler\CommandHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: command.bus }

    ForkCMS\Modules\Extensions\Domain\Module\ModuleInstaller:
      tags:
        - { name: forkcms.module.installer }

    ForkCMS\Core\Domain\Router\ModuleRouteLoader:
      bind:
        $locator: '@file_locator'
        $env: '%kernel.environment%'
      tags:
        - { name: routing.loader }

    Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface:
      tags:
        - { name: controller.argument_value_resolver }

    ForkCMS\Modules\Backend\Domain\Action\ActionControllerInterface:
      tags:
        - { name: forkcms.backend.action }

    Twig\Extension\ExtensionInterface:
      tags:
        - { name: twig.extension }

    ForkCMS\Modules\Internationalisation\Domain\Importer\ImporterInterface:
      tags:
        - { name: forkcms.translation.importer }
