services:
  # default configuration for services in Fork when they import this file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    ForkCMS\Core\Domain\MessageHandler\CommandHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: command.bus }

    ForkCMS\Core\Domain\MessageHandler\EventHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: event.bus }

    ForkCMS\Modules\Extensions\Domain\Module\ModuleInstaller:
      tags:
        - { name: forkcms.module.installer }

    ForkCMS\Core\Domain\Router\ModuleRouteLoader:
      bind:
        $locator: '@file_locator'
        $env: '%kernel.environment%'
      tags:
        - { name: routing.loader }
