parameters:
  fork.is_installed: false
  fork.form.theme: '@@ForkCMSInstaller/form_theme.html.twig'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      string $rootDir: '%kernel.project_dir%'
      bool $forkIsInstalled: '%fork.is_installed%'

  _instanceof:
    ForkCMS\Core\Domain\MessageHandler\CommandHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: command.bus }

    ForkCMS\Core\Domain\MessageHandler\EventHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: event.bus }


  ForkCMS\Core\Installer\:
    resource: '../src/Core/Installer/*'
    exclude:
      - '../src/Core/Installer/Console'
      - '../src/Core/Installer/Controller'
      - '../src/Core/Installer/Domain/Installer/InstallerConnectionFactory.php'

  ForkCMS\Core\Installer\Controller\:
    resource: '../src/Core/Installer/Controller/*'
    public: true

  ForkCMS\Modules\Extensions\Domain\:
    resource: '../src/Modules/Extensions/Domain/*'

  ForkCMS\Modules\Extensions\Domain\Module\ModuleInstallerLocator:
    arguments:
      - !tagged_iterator { tag: 'forkcms.module.installer' }

  ForkCMS\Modules\Backend\Domain\:
    resource: '../src/Modules/Backend/Domain/*'
    exclude:
      - '../src/Modules/Backend/Domain/Module/Module.php'
