parameters:
  fork.is_installed: false
  fork.form.theme: '@@ForkCMSInstaller/form_theme.html.twig'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      string $rootDir: '%kernel.project_dir%'

  _instanceof:
    ForkCMS\Core\Domain\MessageHandler\CommandHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: command.bus }

    ForkCMS\Core\Domain\MessageHandler\EventHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: event.bus }

    ForkCMS\Core\Domain\Module\ModuleInstaller:
      tags:
        - { name: forkcms.module.installer }

  ForkCMS\Core\Installer\:
    resource: '../src/Core/Installer/*'
    exclude:
      - '../src/Core/Installer/Console'
      - '../src/Core/Installer/Controller'
      - '../src/Core/Installer/Domain/Installer/InstallerConnectionFactory.php'

  ForkCMS\Core\Installer\Controller\:
    resource: '../src/Core/Installer/Controller/*'
    public: true

  doctrine.dbal.connection_factory:
    class: ForkCMS\Core\Installer\Domain\Installer\InstallerConnectionFactory
    arguments:
      - "%doctrine.dbal.connection_factory.types%"

  ForkCMS\Core\Domain\Module\ModuleInstallerLocator:
    arguments:
      - !tagged_iterator { tag: 'forkcms.module.installer' }

  module_installers:
    namespace: ForkCMS\Modules\
    resource: '../src/Modules/*/Installer'
