# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
  database.name: '%env(FORK_DATABASE_NAME)%'
  kernel.secret: '%env(APP_SECRET)%'

#  fork.is_installed: true
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
#      $commandBus: '@command_bus' # Generic // This should be replaced with the Messenger component
#      $database: '@database'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/Cache/'
      - '../src/Console/'
      - '../src/Kernel.php'
      - '../src/Core/'
      - '../src/Files/'
      - '../src/Modules/'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
#  App\Controller\:
#    resource: '../src/Controller/'
#    tags: [ 'controller.service_arguments' ]

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
#
#  Twig\Loader\LoaderInterface: '@twig.loader'
#  SpoonDatabase: '@database'
#
#  ForkCMS\App\ForkController:
#
#  fork.kernel:
#    alias: Symfony\Component\HttpKernel\KernelInterface
#    public: true
#
#  command_bus:
#    # @TODO deprecated replace later in this PR with the symfony commands
#    class: SimpleBus\Message\Bus\Middleware\MessageBusSupportingMiddleware
#
#  file_locator.public:
#    alias: file_locator
#    public: true
#  logger.public:
#    alias: logger
#    public: true
#  command_bus.public:
#    alias: command_bus
#    public: true
#  # @TODO reactivate mailmotor
#  #mailmotor.factory.public:
#  #    alias: mailmotor.factory
#  #    public: true
#  database:
#    class: SpoonDatabase
#    public: true
#    arguments:
#      - "%database.driver%"
#      - "%database.host%"
#      - "%database.user%"
#      - "%database.password%"
#      - "%database.name%"
#      - "%database.port%"
#    calls:
#      - [ execute, [ 'SET CHARACTER SET :charset, NAMES :charset, time_zone = "+0:00"', { 'charset': 'utf8mb4' } ] ]
#      # The following line removes the ONLY_FULL_GROUP_BY from the sessions sql_mode, it was added in 5.7
#      # and caused some queries to break.
#      - [ execute, [ 'SET sql_mode = REPLACE(@@SESSION.sql_mode, "ONLY_FULL_GROUP_BY", "")' ] ]
#      - [ setDebug, [ "%kernel.debug%" ] ]
#  mailer_configurator:
#    class: Common\Mailer\Configurator
#    tags:
#      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
#      - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
#    arguments:
#      - '@Common\ModulesSettings'
#      - "@service_container"
#
#  cache.filesystem.adapter:
#    class: League\Flysystem\Adapter\Local
#    arguments:
#      - "%kernel.cache_dir%"
#  cache.adapter.array:
#    class: Symfony\Component\Cache\Adapter\ArrayAdapter
#    arguments:
#      - "%kernel.cache_dir%"
#  cache.filesystem.filesystem:
#    class: League\Flysystem\Filesystem
#    arguments:
#      - "@cache.filesystem.adapter"
#  cache.adapter:
#    class: MatthiasMullie\Scrapbook\Adapters\Flysystem
#    arguments:
#      - "@cache.filesystem.filesystem"
#  cache.buffer:
#    class: MatthiasMullie\Scrapbook\Buffered\BufferedStore
#    arguments:
#      - "@cache.adapter"
#  cache.pool:
#    class: MatthiasMullie\Scrapbook\Psr6\Pool
#    public: true
#    arguments:
#      - "@cache.buffer"
#  cache.backend_navigation:
#    class: Backend\Core\Engine\NavigationCache
#    public: true
#    arguments:
#      - "@database"
#      - "@cache.pool"
#
#  Common\ModulesSettings:
#    public: true
#    arguments:
#      - "@database"
#      - "@cache.pool"
#      - "%fork.is_installed%"
#
#  fork.cookie:
#    class: Common\Core\Cookie
#    public: true
#
#  fork.cookie_setter:
#    class: Common\EventListener\ForkCookieSetter
#    arguments:
#      - "@fork.cookie"
#    tags:
#      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
#
#  fork.controller_init:
#    class: Common\EventListener\ApplicationSetterListener
#    tags:
#      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 2 }
#
#  fork.api_setup:
#    class: Common\EventListener\ApiSetupListener
#    arguments:
#      - '@Symfony\Component\HttpKernel\KernelInterface'
#    tags:
#      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1 }
#
#  ForkCMS\Utility\Module\CopyContentToOtherLocale\CopyContentFromModulesToOtherLocaleManager:
#    public: true
#
#  fork.response_securer:
#    class: Common\EventListener\ResponseSecurer
#    tags:
#      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
#
#  ForkCMS\Utility\Geolocation:
#    public: true
#
#  ForkCMS\Utility\Thumbnails:
#    public: true
#    arguments:
#      - "%site.path_www%"
#
#  ForkCMS\Utility\Csv\Writer:
#    public: true
#    arguments:
#      - "%kernel.charset%"
#
#  ForkCMS\Utility\Csv\Reader:
#    public: true
#
#  Common\Core\Twig\Extensions\IncludeOnceExtension:
#    public: false
#    tags:
#      - { name: twig.extension }
#
#  Common\BlockEditor\Twig\ParseBlocksExtension:
#    public: true
#    autowire: true
#    tags:
#      - { name: twig.extension }
#
#  Console\Locale\ImportLocaleCommand:
#    public: false
#    autowire: true
#    tags:
#      - { name: console.command }
#
#  Console\Thumbnails\GenerateThumbnailsCommand:
#    public: false
#    autowire: true
#    tags:
#      - { name: console.command }
#
#  Backend\Modules\Locale\Engine\CacheBuilder:
#    public: true
#    autowire: true
#
#  Twig\Extension\StringLoaderExtension:
#    autowire: true
#    tags:
#      - { name: twig.extension }
#
#  ForkCMS\Google\TagManager\DataLayer:
#    public: true
#
#  ForkCMS\Google\TagManager\TagManager:
#    public: true
#
#  ForkCMS\Privacy\ConsentDialog:
#    public: true
#    arguments:
#      - '@Common\ModulesSettings'
#      - "@fork.cookie"
#
#  templating: #@TODO check this
#    class: Frontend\Core\Engine\TwigTemplate
