services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Backend\Modules\Location\Domain\Location\LocationRepository:
        public: true

    Backend\Modules\Location\Domain\LocationSetting\LocationSettingRepository:
        public: true
