imports:
  - { resource: commands.yaml }
  - { resource: repositories.yaml }

services:
    Backend\Modules\Location\Domain\Location\Command\CopyLocationWidgetsToOtherLocale:
        tags:
            - { name: fork.copy_module_to_other_locale }
