services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ForkCMS\Modules\Faq\Domain\Category\CategoryRepository:

    ForkCMS\Modules\Faq\Domain\Question\QuestionRepository:

    ForkCMS\Modules\Faq\Domain\Feedback\FeedbackRepository:
