twig:
  default_path: '%kernel.project_dir%/src/Core/Installer/Resources/views'
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  form_themes:
    - '%fork.form.theme%'
  paths:
    '%kernel.project_dir%/src/Core/Installer/Resources/views': ForkCMSInstaller
