webpack_encore:
  # The path where Encore is building the assets - i.e. Encore.setOutputPath()
  output_path: '%kernel.project_dir%/public/build/installer'

  builds:
    installerConfig: '%kernel.project_dir%/public/build/installer'
