services:
    _defaults:
        autowire: true
        autoconfigure: true

    Backend\Modules\MediaGalleries\Console\MediaGalleryDeleteAllCommand:
        tags:
            - { name: console.command }
