#services:
#    _defaults:
#        autowire: true
#        autoconfigure: true
#        public: true
#
#    ForkCMS\Modules\ContentBlocks\Domain\ContentBlock\Command\CreateContentBlockHandler:
#        tags:
#            - { name: command_handler, handles: ForkCMS\Modules\ContentBlocks\Domain\ContentBlock\Command\CreateContentBlock }
#
#    ForkCMS\Modules\ContentBlocks\Domain\ContentBlock\Command\UpdateContentBlockHandler:
#        tags:
#            - { name: command_handler, handles: ForkCMS\Modules\ContentBlocks\Domain\ContentBlock\Command\UpdateContentBlock }
#
#    ForkCMS\Modules\ContentBlocks\Domain\ContentBlock\Command\DeleteContentBlockHandler:
#        tags:
#            - { name: command_handler, handles: ForkCMS\Modules\ContentBlocks\Domain\ContentBlock\Command\DeleteContentBlock }
#
#    ForkCMS\Modules\ContentBlocks\Domain\ContentBlock\Command\CopyContentBlocksToOtherLocaleHandler:
#        tags:
#            - { name: command_handler, handles: ForkCMS\Modules\ContentBlocks\Domain\ContentBlock\Command\CopyContentBlocksToOtherLocale }
