imports:
  - { resource: commands.yaml }
  - { resource: repositories.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ForkCMS\Modules\ContentBlocks\Api\ApiController: ~

    content_blocks.copy:
        class: ForkCMS\Modules\ContentBlocks\Domain\ContentBlock\Command\CopyContentBlocksToOtherLocale
        tags:
            - { name: fork.copy_module_to_other_locale }
