services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Backend\Modules\Pages\Domain\Page\Command\CopyPagesToOtherLocaleHandler:
        tags:
            - { name: command_handler, handles: Backend\Modules\Pages\Domain\Page\Command\CopyPagesToOtherLocale }

    Backend\Modules\Pages\Domain\Page\Command\CreatePageHandler:
        tags:
            - { name: command_handler, handles: Backend\Modules\Pages\Domain\Page\Command\CreatePage }

    Backend\Modules\Pages\Domain\Page\Command\UpdatePageHandler:
        tags:
            - { name: command_handler, handles: Backend\Modules\Pages\Domain\Page\Command\UpdatePage }
